add model mlpmixer (from geniuspatrick)
mindspore-lab/mindcv pull request #518
Opened 2023-03-14 04:47 UTC by XixinYang

Thank you for your contribution to the MindCV repo.
Before submitting this PR, please make sure:

- [ ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Motivation

(Write your motivation for proposed changes here.)

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

2023-03-15 07:10 UTC, geniuspatrick requested changes
you also need to add an entry in `__init__.py` for model registration.

2023-03-15 07:10 UTC, geniuspatrick commented on mindcv/models/mlpmixer.py
> +# Copyright 2022 Huawei Technologies Co., Ltd
remove copyright

2023-03-16 04:28 UTC, XixinYang commented on mindcv/models/mlpmixer.py
> +# Copyright 2022 Huawei Technologies Co., Ltd
the both are done

2023-03-16 08:40 UTC, geniuspatrick approved these changes

2023-03-16 08:40 UTC, Songyuanwei approved these changes

2023-03-16 08:40 UTC, merged