[Feature] add model script of cait
mindspore-lab/mindcv pull request #547
Opened 2023-03-20 11:53 UTC by wcrzlh

Thank you for your contribution to the MindCV repo.
Before submitting this PR, please make sure:

- [ ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Motivation

The model script of cait is added.

## Test Plan

Please use 'create_model' part for testing models in cait.

## Related Issues and PRs

Related issue: https://github.com/mindspore-lab/mindcv/issues/424

2023-03-21 02:00 UTC, geniuspatrick requested changes

2023-03-21 02:00 UTC, geniuspatrick commented on mindcv/models/cait.py
> +def cait_XXS24_224(pretrained: bool = False, num_classes: int = 1000, in_channels=3, **kwargs) -> CaiT:
这个函数名也是

2023-03-21 03:50 UTC, wcrzlh commented on mindcv/models/cait.py
> +
added

2023-03-21 03:50 UTC, wcrzlh commented on mindcv/models/cait.py
> +class Class_Attention(nn.Cell):
是的

2023-03-21 03:52 UTC, wcrzlh commented on mindcv/models/cait.py
> +        "talking head trick"
It is a trick used in cait. I have deleted this comment line.

2023-03-21 03:52 UTC, wcrzlh commented on mindcv/models/cait.py
> +
deleted

2023-03-21 03:52 UTC, wcrzlh commented on mindcv/models/cait.py
> +    def _init_weights(self) -> None:
fixed

2023-03-21 03:53 UTC, wcrzlh commented on mindcv/models/cait.py
> +def cait_XXS24_224(pretrained: bool = False, num_classes: int = 1000, in_channels=3, **kwargs) -> CaiT:
原作者实现中写的就是这样的函数名

2023-03-24 06:43 UTC, geniuspatrick approved these changes

2023-03-24 06:43 UTC, merged