fix metric bugs for mindspore 2.0
mindspore-lab/mindcv pull request #567
Opened 2023-03-24 06:54 UTC by SamitHuang

Thank you for your contribution to the MindCV repo.
Before submitting this PR, please make sure:

- [ ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Motivation

(Write your motivation for proposed changes here.)

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

2023-03-24 07:15 UTC, Songyuanwei approved these changes

2023-03-24 07:19 UTC, geniuspatrick requested changes

2023-03-24 07:19 UTC, geniuspatrick commented on mindcv/utils/trainer_factory.py
> +    if ms.__version__[:3] in ["2.0"]:
1. mindspore2.0先不要在我们v0.2里面出现
2. 不要这样写。用try catch

2023-06-02 04:02 UTC, geniuspatrick commented
The MS2.0 now has metrics in `nn` package. Closing.

2023-06-02 04:02 UTC, closed without merging