[Feature] update model script, add training recipe and trained weights of GhostNet
mindspore-lab/mindcv pull request #597
Opened 2023-04-10 06:58 UTC by The-truthh

Thank you for your contribution to the MindCV repo.
Before submitting this PR, please make sure:

- [ ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Motivation

update model script, add training recipe and trained weights of GhostNet

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

Related issue: closes #428

2023-05-08 02:16 UTC, geniuspatrick requested changes

2023-05-08 02:16 UTC, geniuspatrick commented on mindcv/models/ghostnet.py
> +from .layers.conv_norm_act import Conv2dNormActivation
不要使用这个接口

2023-05-09 06:33 UTC, The-truthh commented on mindcv/models/ghostnet.py
> +from .layers.conv_norm_act import Conv2dNormActivation
已修改

2023-05-23 13:35 UTC, SamitHuang approved these changes

2023-05-23 13:37 UTC, merged