coat_mini update
mindspore-lab/mindcv pull request #662
Opened 2023-05-24 08:20 UTC by SunJuil-Ty

Thank you for your contribution to the MindCV repo.
Before submitting this PR, please make sure:

- [ ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Motivation

(Write your motivation for proposed changes here.)

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

2023-05-30 02:45 UTC, geniuspatrick requested changes

2023-05-30 02:45 UTC, geniuspatrick commented on configs/coat/README.md
> +| coat_mini | D910x8-G | 81.08 | 95.34 | 10.34 | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/coat/coat_mini_ascend.yaml) | [weights](https://download.mindspore.cn/toolkits/mindcv
coat_mini-57c5bce7

2023-05-30 02:45 UTC, geniuspatrick commented on configs/coat/README.md
> +| coat_mini | D910x8-G | 81.08 | 95.34 | 10.34 | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/coat/coat_mini_ascend.yaml) | [weights](https://download.mindspore.cn/toolkits/mindcv
短横线

2023-05-30 02:45 UTC, geniuspatrick commented on configs/coat/coat_mini_ascend.yaml
> +scheduler: 'warmup_cosine_decay'
cosine_decay即可

2023-05-30 02:45 UTC, geniuspatrick commented on mindcv/models/coat.py
> +    'coat_mini': _cfg(url='https://download.mindspore.cn/toolkits/mindcv/coat/coat_mini_57c5bce7.ckpt'),
同上

2023-05-31 10:34 UTC, SunJuil-Ty commented on mindcv/models/coat.py
> +    'coat_mini': _cfg(url='https://download.mindspore.cn/toolkits/mindcv/coat/coat_mini_57c5bce7.ckpt'),
已修改

2023-05-31 10:34 UTC, SunJuil-Ty commented on configs/coat/coat_mini_ascend.yaml
> +scheduler: 'warmup_cosine_decay'
已修改

2023-05-31 10:34 UTC, SunJuil-Ty commented on configs/coat/README.md
> +| coat_mini | D910x8-G | 81.08 | 95.34 | 10.34 | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/coat/coat_mini_ascend.yaml) | [weights](https://download.mindspore.cn/toolkits/mindcv
已修改

2023-06-07 10:18 UTC, geniuspatrick approved these changes

2023-06-12 09:44 UTC, SamitHuang approved these changes

2023-06-12 09:44 UTC, merged