Support amp level in validation
mindspore-lab/mindcv pull request #668
Opened 2023-06-02 07:15 UTC by SamitHuang

Thank you for your contribution to the MindCV repo.
Before submitting this PR, please make sure:

- [ ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Motivation

目前 validate.py 跑 Transformer类网络超慢（910, >半小时），比训练一轮的时间都要长，原因在于transformer训练是混合精度，边训边验也是，但validate却只能是O0。

现改为validate也根据yaml脚本的amp_level来配置混合精度，也方便与边训边验的结果的同步。

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

2023-06-02 07:21 UTC, CaitinZhao commented on validate.py
> +    ms.amp.auto_mixed_precision(network, amp_level=args.amp_level)
这么改可能有个问题，GPU的BN推理不支持fp16，可能会对已有GPU网络推理有影响

2023-06-02 07:22 UTC, CaitinZhao commented on validate.py
> +    ms.amp.auto_mixed_precision(network, amp_level=args.amp_level)
推理慢主要是MatMul慢，是不是在套件里单独包一下，Ascend只能走fp16？

2023-06-02 07:28 UTC, SamitHuang commented on validate.py
> +    ms.amp.auto_mixed_precision(network, amp_level=args.amp_level)
GPU边训边验时，BN也是不支持fp16，应该不影响。只是结果会与Ascend不一样，但这个应该是另一个问题了。

2023-06-21 02:35 UTC, geniuspatrick requested changes
此改动会对库上所有模型的精度报告有影响。也许我们需要对所有模型的预训练权重的精度进行重新全量验证

2023-06-30 01:38 UTC, geniuspatrick commented
duplicate of #676

2023-06-30 01:38 UTC, closed without merging