feat: add jsd loss and asymmetric loss
mindspore-lab/mindcv pull request #682
Opened 2023-06-12 09:05 UTC by wcrzlh

Thank you for your contribution to the MindCV repo.
Before submitting this PR, please make sure:

- [ ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Motivation

Jsd loss and asymmetric loss are added.

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

Related issue: https://github.com/mindspore-lab/mindcv/issues/621

2023-06-21 02:02 UTC, geniuspatrick requested changes

2023-06-21 02:02 UTC, geniuspatrick commented on mindcv/loss/asymmetric.py
> +        los_pos = labels * ops.Log()(ops.clip_by_value(xs_pos, clip_value_min=Tensor(self.eps)))
这些算子统一看下有没有函数式接口的，有就替换下

2023-06-28 14:10 UTC, vigo999 commented on mindcv/loss/asymmetric.py
> +        los_pos = labels * ops.Log()(ops.clip_by_value(xs_pos, clip_value_min=Tensor(self.eps)))
@wcrzlh finished???

2023-06-29 06:09 UTC, wcrzlh commented on mindcv/loss/asymmetric.py
> +        los_pos = labels * ops.Log()(ops.clip_by_value(xs_pos, clip_value_min=Tensor(self.eps)))
finished

2023-06-29 06:25 UTC, geniuspatrick commented
please add some unit tests

2023-07-05 09:51 UTC, wcrzlh commented
added

2023-07-08 12:02 UTC, SamitHuang approved these changes

2023-07-10 02:39 UTC, geniuspatrick approved these changes

2023-07-10 02:39 UTC, merged