feat: support custom amp cast list
mindspore-lab/mindcv pull request #685
Opened 2023-06-14 09:57 UTC by The-truthh

Thank you for your contribution to the MindCV repo.
Before submitting this PR, please make sure:

- [ ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Motivation

support custom amp cast list

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

2023-06-28 14:16 UTC, vigo999 commented on config.py
> +    group.add_argument('--amp_cast_list', type=str, default=None,
can rewrite this help msg? can't be easily understand

2023-06-28 14:23 UTC, vigo999 commented
what is the difference with original api below?
[mindcv/utils/amp.py](https://www.mindspore.cn/docs/en/r2.0/_modules/mindspore/train/amp.html#auto_mixed_precision)

2023-06-29 02:17 UTC, The-truthh commented
The difference of function 'auto_mixed_precision' between mindspore and mindcv is that mindcv supports custom black list and white list. If we use the default black list and white list, the effect is the same.

2023-06-29 06:23 UTC, geniuspatrick requested changes

2023-06-29 06:23 UTC, geniuspatrick commented on mindcv/utils/trainer_factory.py
> +    # process amp with custom cast list
先只对自定义训练逻辑实现自定义黑白名单

2023-06-29 06:23 UTC, geniuspatrick commented on mindcv/utils/trainer_factory.py
>      if not require_customized_train_step(ema, clip_grad, gradient_accumulation_steps):
这个代码块下的逻辑不要改变，保持绝对的兼容性

2023-06-29 06:23 UTC, geniuspatrick commented on mindcv/utils/trainer_factory.py
>      else:  # require customized train step
对这个分支，增添自定义名单逻辑

2023-06-29 06:23 UTC, geniuspatrick commented on mindcv/utils/amp.py
> +AMP_WHITE_LIST = (
有些函数和变量可以从mindspore导入的，直接导入；除非我们需要覆盖或重载函数

2023-07-08 12:48 UTC, SamitHuang approved these changes
Update training tutorial for this new feature of amp customization.

2023-07-08 12:56 UTC, SamitHuang approved these changes
Update training tutorial for this new feature of amp customization.

2023-07-10 07:16 UTC, geniuspatrick approved these changes

2023-07-10 07:16 UTC, geniuspatrick commented on config.py
> +                            'For O2, cast all ops except for the list to FP16. '
ex1:  amp_cast_list: "['nn.Conv2D']"

2023-07-10 08:20 UTC, geniuspatrick requested changes

2023-07-10 08:20 UTC, geniuspatrick commented on config.py
> +                            'For O2, cast all ops except for the list to FP16. '
examples & explanation

2023-07-11 08:14 UTC, geniuspatrick approved these changes

2023-07-11 08:15 UTC, merged