refactor: uniform all model names and correct many other text errors;
mindspore-lab/mindcv pull request #701
Opened 2023-07-06 08:18 UTC by XixinYang

Thank you for your contribution to the MindCV repo.
Before submitting this PR, please make sure:

- [x] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved terminology
- [ ] You have added unit tests

## Motivation

### 统一库上所有模型名称
#### 此PR下：
①模型名：configs目录下的子文件夹名（configs/*）与mindcv/models目录下的模型文件名（mindcv/models/*.py）保持一致；
②模型规格名：
mindcv/models/*.py：__all__内模型名称、default_cfgs.keys()中的模型名称、register_model处模型函数名
configs/*/*.yaml：yaml文件名、文件内`model`参数处模型名称
configs/*/*.md：`results`表格中预训练权重链接里的模型名称
以上三处模型名称保持一致
另：configs/*/*.md：`results`表格中的`model`列内容与上述相同，但可能含有大写字母（即：此处模型名与论文保持一致）；

#### 遗留问题：
①mobilenet_v2、visformer v2、repmlpnet、xcit需要修改云上ckpt文件名，可能仍有其他模型需要修改ckpt链接，待排查；
②其他可能遗漏的问题，待review和进一步排查；

### 其它修改
①修改过程中遇到的关联文件，如inference.md，readme.md等；
②configs/*/*.md的文章标题与论文中模型正式名称保持一致；
③benchmark_results.md
④其他文本错误（如：GoogLENet ->GoogLeNet 等等）

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

2023-07-06 09:36 UTC, The-truthh commented on configs/bit/README.md
> +| BiT_resnet50   | D910x8-G | 76.81     | 93.17     | 25.55     | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/bit/bit_resnet50_ascend.yaml)   | [weights](https://download.mindspo
权重地址变了，ckpt不能正常下载了

2023-07-06 09:36 UTC, The-truthh commented on configs/convnextv2/README.md
> +| ConvNeXt_V2_tiny | D910x8-G | 82.43     | 95.98     | 28.64      | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/convnextv2/convnext_v2_tiny_ascend.yaml) | [weights](https://down
权重地址错误

2023-07-06 09:36 UTC, The-truthh commented on configs/shufflenetv2/README.md
> +| ShuffleNet_V2_05 | D910x8-G | 60.53     | 82.11     | 1.37       | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/shufflenetv2/shufflenet_v2_0.5_ascend.yaml) | [weights](https://d
权重地址错误

2023-07-06 09:36 UTC, The-truthh commented on configs/shufflenetv1/shufflenet_v1_g3_05_ascend.yaml
> +model: "shufflenet_v1_g3_05"
改为050会不会更好一点

2023-07-06 09:36 UTC, The-truthh commented on configs/swintransformerv2/README.md
> +| Swin_V2_tiny_window8 | D910x8-G | 81.42     | 95.43     | 28.78      | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/swintransformerv2/swin_v2_tiny_window8_ascend.yaml) | [weight
权重地址错误

2023-07-06 09:36 UTC, The-truthh commented on configs/visformer/README.md
> +| Visformer_V2_tiny  | D910x8-G | 78.82     | 94.41     | 9.38       | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/visformer/visformer_v2_tiny_ascend.yaml)  | [weights](https://d
权重地址错误

2023-07-10 03:58 UTC, geniuspatrick commented on mindcv/models/__init__.py
> -__all__.extend(["InceptionV3", "inception_v3"])
["InceptionV3", "inception_v3"]

2023-07-11 02:43 UTC, geniuspatrick requested changes

2023-07-11 02:43 UTC, geniuspatrick commented on configs/bit/BiT_resnet101_ascend.yaml
文件名先不要改

2023-07-11 02:43 UTC, geniuspatrick commented on configs/bit/README.md
> +| BiT_resnet50   | D910x8-G | 76.81     | 93.17     | 25.55     | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/bit/BiT_resnet50_ascend.yaml)   | [weights](https://download.mindspo
模型名和链接名也不要改

2023-07-11 02:43 UTC, geniuspatrick commented on configs/bit/README.md
> +| BiT_resnet50   | D910x8-G | 76.81     | 93.17     | 25.55     | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/bit/BiT_resnet50_ascend.yaml)   | [weights](https://download.mindspo
所有的链接名都不用改

2023-07-11 02:43 UTC, geniuspatrick commented on configs/crossvit/crossvit_15_ascend.yaml
> -model: 'crossvit15'
为什么有的数字前有下划线，有的之前没有

2023-07-11 02:43 UTC, geniuspatrick commented on configs/densenet/README.md
> +| densenet121 | D910x8-G | 75.64     | 92.84     | 8.06       | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/densenet/densenet121_ascend.yaml) | [weights](https://download.mindspo
这里又把下划线去掉了？

2023-07-11 02:43 UTC, geniuspatrick commented on configs/mnasnet/README.md
> +| mnasnet_050 | D910x8-G | 68.07     | 88.09     | 2.14       | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/mnasnet/mnasnet_050_ascend.yaml) | [weights](https://download.mindspor
这个名字的修改很好

2023-07-11 02:43 UTC, geniuspatrick commented on configs/rexnet/rexnet_09_ascend.yaml
> +model: "rexnet_09"
这个怎么模型名字由13变成09了

2023-07-11 02:43 UTC, geniuspatrick commented on docs/en/tutorials/inference.md
> +    ['BiT_resnet50',
bit小写？

2023-07-11 02:43 UTC, geniuspatrick commented on mindcv/models/convnext.py
> -    """Get ConvNeXt_v2 atto model.
没必要改

2023-07-11 02:43 UTC, geniuspatrick commented on mindcv/models/swintransformerv2.py
> +    "swin_v2_tiny_window16": _cfg(url=""),
这个v2前面加下划线的意义是？

2023-07-11 03:41 UTC, XixinYang commented on configs/crossvit/crossvit_15_ascend.yaml
> -model: 'crossvit15'
跟ckpt的命名统一，有的ckpt文件名在之前修改的时候就没有加下划线

2023-07-11 06:51 UTC, XixinYang commented on configs/rexnet/rexnet_09_ascend.yaml
> +model: "rexnet_09"
09, 10和13的配置文件除了model参数外全都一致，可能是上传过程系统识别问题导致，已经核查过这个改动下其他配置参数没有改动

2023-07-11 06:54 UTC, XixinYang commented on docs/en/tutorials/inference.md
> +    ['BiT_resnet50',
为了跟ckpt模型名对齐，没有改成小写

2023-07-11 07:03 UTC, XixinYang commented on configs/densenet/README.md
> +| densenet121 | D910x8-G | 75.64     | 92.84     | 8.06       | [yaml](https://github.com/mindspore-lab/mindcv/blob/main/configs/densenet/densenet121_ascend.yaml) | [weights](https://download.mindspo
跟ckpt对齐

2023-07-12 01:43 UTC, geniuspatrick approved these changes
LGTM

2023-07-12 10:46 UTC, SamitHuang approved these changes

2023-07-13 03:08 UTC, merged